version: '2'

services:
    db:
        image: postgres
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - data-volume:/var/lib/postgresql/data

    app:
        build: ./app
        command: /app/scripts/runserver.sh
        ports:
          - "12345:12345"
        depends_on:
            - db

volumes:
    data-volume:
